### ISSUE TITLE
False positives for lists in Yaml frontmatter

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#88] opened 2018-10-13 00:50 UTC
Sees the rule about no content before the H1 is interpreting lists in the frontmatter as Markdown.
EX: https://github.com/MicrosoftDocs/windows-driver-docs/pull/927

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2904c9e-0365-28cc-0315-98ac5381145c
* Version Independent ID: eb4d05d0-c482-2e8d-d43f-57ddee93bd3f
* Content: [Markdown Headings - Contributor Guide](https://docs.microsoft.com/en-us/contribute/validation-reference/markdown-headings)
* Content Source: [Contribute/validation-reference/markdown-headings.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/validation-reference/markdown-headings.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by meganbradley** [comment] 2018-10-15 01:53
Thanks @nschonni . I filed an internal bug to investigate this issue.
@TinaLiuGirl @v-caxian @seshenoy see bug 44850 in ceapex.

**Comment by JasonWHowell** [comment] 2018-10-15 18:32
@meganbradley Looks like you have it covered for now. Should we close out the issue, or wait a while for a followup?

**Comment by meganbradley** [comment] 2018-10-16 01:48
@JasonWHowell please leave it open for now. I'll update and close when the issue is fixed.

**Comment by meganbradley** [comment] 2018-11-30 21:21
Yes, closing this issue. The problem was a BOM before the YML block, and it is now fixed. We have a validation in spec to catch these.

**Closed by meganbradley** 2018-11-30 21:21 UTC
