### ISSUE TITLE
Indices and ranges making confuse with index value ^0 for the end index or ^1 for the end index 

### ISSUE THREAD

**Issue by hetramlakhera** [MicrosoftDocs/Contribute#244] opened 2019-04-16 12:48 UTC
Indices and ranges
Ranges and indices provide a succinct syntax for specifying subranges in an array, Span<T>, or ReadOnlySpan<T>.

You can specify an index from the end. You specify from the end using the ^ operator. You are familiar with array[2] meaning the element "2 from the start". Now, array[^2] means the element "2 from the end". The index ^0 means "the end", or the index that follows the last element.

You can specify a range with the range operator: ... For example, 0..^0 specifies the entire range of the array: 0 from the start up to, but not including 0 from the end. Either operand may use "from the start" or "from the end". Furthermore, either operand may be omitted. The defaults are 0 for the start index, **and ^0 for the end index.**

Let's look at a few examples. Consider the following array, annotated with its index from the start and from the end:
var words = new string[]
{
                // index from start    index from end
    "The",      // 0                   ^9
    "quick",    // 1                   ^8
    "brown",    // 2                   ^7
    "fox",      // 3                   ^6
    "jumped",   // 4                   ^5
    "over",     // 5                   ^4
    "the",      // 6                   ^3
    "lazy",     // 7                   ^2
    **"dog"       // 8                   ^1**
};

**Console.WriteLine($"The last word is {words[^1]}");
// writes "dog"**

**Comment by BillWagner** [comment] 2019-04-16 13:17
this is a duplicate of dotnet/docs#3966

Closing.

**Closed by BillWagner** 2019-04-16 13:17 UTC

**Comment by hetramlakhera** [comment] 2019-04-16 13:39
This duplicate only to show where the text is confusing.i puted text in bold

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
