### ISSUE TITLE
Broken link on "Preview Ribbon Sample"; and https://github.com/MicrosoftDocs/win32-pr not found

### ISSUE THREAD

**Issue by kiewic** [MicrosoftDocs/Contribute#267] opened 2019-07-27 02:04 UTC
I'm looking for the sample described on "Docs / Windows / Windows Ribbon Framework / Ribbon Framework Samples / [Preview Ribbon Sample](https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-previewribbon)" page.

The Contributing link on this page is broken too: https://github.com/MicrosoftDocs/win32-pr/blob/live/desktop-src/windowsribbon/windowsribbon-previewribbon.md

Any idea where I can find the sample? Or what team owns these docs?

Thanks,
Gilberto

**Comment by JasonWHowell** [comment] 2019-07-30 23:32
@Karl-Bridge-Microsoft could you please advise if you know where the sample went...

The MSDN link isn't working: https://go.microsoft.com/fwlink/p/?linkid=177607
Redirects to https://archive.msdn.microsoft.com/PreviewRibbon

Thanks, Jason

**Comment by markgort86** [comment] 2019-08-24 10:53
I asked a question about this issue on the following page: [Windows Desktop Ribbon](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/5c61d2cd-d773-43d4-8368-0d2b0a6865a1/where-can-i-download-the-preview-ribbon-sample?forum=windowsribbondevelopment. 
)

Maybe the people over there have an answer on this question.

**Comment by adambarlow** [comment] 2019-09-03 22:31
@kiewic this sample refers to a preview tool for authoring ribbons using this older Win7 SDK API:
https://docs.microsoft.com/en-us/windows/win32/windowsribbon/-uiplat-windowsribbon-entry

Is this what you are trying to use?

**Comment by markgort86** [comment] 2019-09-07 11:33
@adambarlow this one: https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-previewribbon. But there is no way to download this software, from the hyperlinks available on that page.

**Comment by Youssef1313** [comment] 2019-11-01 05:57
Are the following files what you search for ?

![image](https://user-images.githubusercontent.com/31348972/68005210-26963300-fc7d-11e9-874a-13404f2e3b91.png)


I've found them in [this repo](https://github.com/aslistener/qtribbon).

**Comment by Jim-Parker** [comment] 2020-01-14 19:40
@kiewic Thanks for reporting this issue. It looks like some answers were provided. I'm going to close this issue, but please let us know if you feel like this still needs resolution.

**Comment by andlabs** [comment] 2020-03-26 02:39
Hi. I'm not the original person asking the question, but I do have the same question *verbatim* — where is the Preview Ribbon Sample for the Windows Ribbon Framework API for Windows 7 is.

@adambarlow yes, the Preview Ribbon Sample is one of the samples for the API you linked. There are eight total samples listed, but that one and the Tutorial are no longer available to download. The rest are available at https://www.microsoft.com/en-us/download/details.aspx?id=9620

In my case, the sample program is of interest to me specifically because it appears to show dynamic ribbon creation, but if this truly isn't possible I'm going to guess that it's just re-running UICC.exe after every change? I can't say what the OP wanted it for; sorry.

@Youssef1313 That list is still around at https://www.microsoft.com/en-us/download/details.aspx?id=9620, but again, it does not include the Preview Ribbon Sample.

**Comment by Karl-Bridge-Microsoft** [comment] 2020-03-26 16:06
@adambarlow - This appears to be a lingering issue. Are the samples in question in an archive somewhere? On somebody's hard drive?

I've checked for Ribbon samples in the MSDN sample archive on GitHub, but not sure if any fit the need (no samples with the name Preview Ribbon Sample): https://github.com/microsoftarchive/msdn-code-gallery-microsoft/search?q=ribbon&unscoped_q=ribbon.

**Comment by andlabs** [comment] 2020-03-26 20:58
If it helps, the file we're asking about was on an old MSDN Archive site that did not get picked up by archive.org very well... or at least that's what I remember, as it's been a while since I tried looking this up.

**Comment by Karl-Bridge-Microsoft** [comment] 2020-04-08 02:31
I just confirmed that the sample is not available in the WIn7.1 SDK download either. As this feature is not under active development, we can't help any further. I will update the docs and remove any reference to this sample. 

As this feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by Jim-Parker** [comment] 2020-04-08 15:18
@Karl-Bridge-Microsoft thank you for the additional research and information. I'm going to close this issue because I think the original question was addressed at this point.

**Closed by Jim-Parker** 2020-04-08 15:18 UTC
Labels: Non-guide issue

**Comment by andlabs** [comment] 2020-04-08 22:10
All right, thanks for the help. If I ever do find it again I'll post an update.
