### ISSUE TITLE
Table alignment

### ISSUE THREAD

**Issue by KingdomOfEnds** [MicrosoftDocs/Contribute#165] opened 2018-12-13 22:49 UTC
Great document - vastly improved my knowledge about the specific flavor of Markdown used. I think the specification for table syntax might have changed given that the rendered example above is all left-aligned. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#tables)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by markgort86** [comment] 2019-08-24 10:56
I think the issue is resolved. All tables are values are alligned correctly. Can you check this on you're end?

**Comment by JasonWHowell** [comment] 2019-10-08 18:21
I've seen that the table alignment is now fixed too. I think we can close out this thread.

**Closed** 2019-10-08 18:21 UTC
Labels: Docs platform issue
