### ISSUE TITLE
Bug in REST API for deletion of Azure Traffic Manager Endpoint

### ISSUE THREAD

**Issue by Mayank1710** [MicrosoftDocs/Contribute#429] opened 2020-08-31 11:56 UTC
Created Traffic Manager endpoint with endpoint type as Azure Endpoint.

But, when I run the REST API version for deleting Traffic Manager Endpoint, I provide endpointtype as nestedEndpoints/  externalEndpoints though I knew it should be azureEndpoints.

I saw the API return status code as 200 (which means deletion is successful) but endpoint won't get deleted as I provided wrong endpoint type, I checked after refreshing the Azure portal

The issue here is the deletion API call returns 200 status code only when deletion of endpoint is successful, but here as I can see, deletion didn't work due to wrong parameters but status code returned is 200. Ideally, the status code returned should be 204. I have created a support request for the same with email- mayank.swaraj@hp.com. I showed the demo to Microsoft support engineer- rivice@microsoft.com as well, He too agreed with it. He told he will take this up to the product team.

![test1](https://user-images.githubusercontent.com/29207204/91717341-f5dd9d80-ebae-11ea-81bf-4220e625f469.JPG)
![test2](https://user-images.githubusercontent.com/29207204/91717347-f7a76100-ebae-11ea-83d5-ea1304b2a0da.JPG)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Jim-Parker** [comment] 2020-09-01 18:36
@Mayank1710 is there an article related to this issue? I'm trying to determine who we can find to help you.

**Comment by BillWagner** [comment] 2020-09-01 18:44
Thanks @Jim-Parker  I looked at the description above, and I don't have any information to help. I'm sorry.

**Comment by JasonWHowell** [comment] 2020-09-01 18:50
This isn't the right forum for this feedback. Jim has messaged @rohinkoul who owns the Azure Traffic Manager docs pages:
https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-endpoint-types

**Comment by Jim-Parker** [comment] 2020-11-03 16:53
@Mayank1710 apologies for the delay in addressing this issue. Because the issue is related to content outside of the contributor I'm going to close this. I've communicated your concerns to @rohinkoul and @jonbeck7 for their review. Thanks.

**Closed by Jim-Parker** 2020-11-03 16:53 UTC
